# Generated by Django 4.1.4 on 2022-12-15 11:47

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=50)),
                ('Description', models.TextField()),
                ('Price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('unique_code', models.UUIDField(default=uuid.uuid1, unique=True)),
                ('Quentity', models.CharField(choices=[('high', 'high'), ('medium', 'medium'), ('low', 'low')], max_length=20)),
            ],
        ),
    ]
